### ISSUE TITLE
希望可以新增  两张人脸图片对比的接口

### ISSUE THREAD

**Issue by lhn137996** [AnyLifeZLB/FaceSearchSDK_Android#3]

**Comment by AnyLifeZLB** [comment]
下周

**Comment by AnyLifeZLB** [comment]
/**
* 评估两张人脸Bitmap的是否同一人
*
* @param mContext
* @param bitmap1
* @param bitmap2
* @return
*/
public static float evaluateFaceSimi(Context mContext, Bitmap bitmap1, Bitmap bitmap2){}

    //Demo 中已经有如下代码了
    val value=VerifyUtils.evaluateFaceSimi(baseContext,
        VerifyUtils.getBitmapFromAssert(baseContext,"model_1.png"),
        VerifyUtils.getBitmapFromAssert(baseContext,"model.jpg"))

    Log.d("VerifyUtils", "value:  $value")
不管什么图只要转为Bitmap ，你可以在Assert 目录放2张图测试一下

https://github.com/AnyLifeZLB/FaceVerificationSDK  V 1.3.4 开始支持 ,更新Demo

**Comment by AnyLifeZLB** [comment]
有需要可以看看是否符合需求
