### ISSUE TITLE
在windows或linux平台运行

### ISSUE THREAD

**Issue by WendellHe** [AnyLifeZLB/FaceSearchSDK_Android#5]
希望提供在服务器上运行的sdk。实现前端提取特征，后端搜索特征的功能。

**Comment by AnyLifeZLB** [comment]
gooood issues

**Comment by AnyLifeZLB** [comment]
本SDK 的目标是Android 定制设备可离线人脸搜索的能力，暂时无打算扩充到Windows/Linux
