### ISSUE TITLE
说实话，体验app还是可以，实际没什么卵用

### ISSUE THREAD

**Issue by cwwei2005** [AnyLifeZLB/FaceSearchSDK_Android#8]
不知道我是不是不会用，还不如我用seetaface做的好用。
我把我的人脸图片放进去再刷脸根本识别不了，在网上找的星爷的照片也无法识别，把预置的照片拿出来扫它才能识别。
说白了就是：不是用app入库的人脸无法识别。

**Comment by AnyLifeZLB** [comment]
yes, you are right

**Comment by AnyLifeZLB** [comment]
![image](https://github.com/AnyLifeZLB/FaceSearchSDK_Android/assets/15169396/abe2469a-c1a0-497c-8da0-9385acfa64e3)
能不能识别出来
1. Threshold(0.8f)    //阈值设置，范围限 [0.75 , 0.95]
2. 通过SDK入库处理的人脸底图质量（不能自己插入一张图，要SDK API insert） 和 要识别的人是否 都是正脸 ，是否有修图等
3. SDK 能力限制，流程问题
4. 天黑了
